### ISSUE TITLE
Database proposal for the REST API

### ISSUE THREAD

**Issue by frankely** [shakenbytes/riot#21]
We need to choose a storage/database option.

**Comment by ernestomancebo** [comment]
MongoDB, CouchDB, Redis, PostgreSQL

**Comment by AngelGarcia13** [comment]
We could use an embedded database as a JSON.

Look at this https://www.npmjs.com/package/diskdb

**Comment by frankely** [comment]
> We could use an embedded database as a JSON.
> 
> Look at this https://www.npmjs.com/package/diskdb
> 
> @ernestomancebo @erickcortorreal @frankely

I like the description of what it is "A Lightweight Disk based JSON Database with a MongoDB like API for Node.".

I think the fact that the API is similar to MongoDB will allows us to move to MongoDB when we need to. 

I like this idea what do you guys think? @ernestomancebo  @erickcortorreal ?

**Comment by erickcortorreal** [comment]
I think it would be a good one to start with, then we decide if need something more powerful like MongoDB and it should be easy to migrate to mongo later.

**Comment by ernestomancebo** [comment]
Ding ding ding, we have a winer lol.

**Comment by frankely** [comment]
Cool then we are using https://www.npmjs.com/package/diskdb
